### ISSUE TITLE
make the divider configurable

### ISSUE THREAD

**Issue by jordens** [quartiq/urukul#3]
* useful for low frequency (e.g. 10 MHz, 100 MHz) reference with AD9910 where divide-by-four is not needed and detrimental
* also needed for bypassing the PLL at 1 GHz direct
* check loop filter/Icp usability at low frequencies

## Roadmap

* [x] add CFG bits for 1/2/4 division
* [x] document old hardware behavior, new behavior
* [x] expose in urukul coredevice driver
* [x] test 1 GHz divide-by-1 PLL bypass

Not in scope:

* [ ] test 10 MHz divide-by-1 100x PLL (assuming loop filter/Icp usability)
* [ ] test 100 MHz divide-by-2 20x PLL (assuming loop filter/Icp usability)

**Comment by jordens** [comment]
1 GHz use case funded by Hosten/IST
